export const COUNTER_INCREASE = 'COUNTER_INCREASE'
export const COUNTER_DECREASE = 'COUNTER_DECREASE'

export const POPULAR_REFRESH = 'POPULAR_REFRESH'
export const POPULAR_REFRESH_SUCCESS = 'POPULAR_REFRESH_SUCCESS'
export const POPULAR_REFRESH_FAIL = 'POPULAR_REFRESH_FAIL'
export const POPULAR_LOADMORE = 'POPULAR_LOADMORE'
export const POPULAR_LOADMORE_SUCCESS = 'POPULAR_LOADMORE_SUCCESS'
export const POPULAR_LOADMORE_FAIL = 'POPULAR_LOADMORE_FAIL'

export const popularTypes = {
  POPULAR_REFRESH,
  POPULAR_REFRESH_SUCCESS,
  POPULAR_REFRESH_FAIL,
  POPULAR_LOADMORE,
  POPULAR_LOADMORE_SUCCESS,
  POPULAR_LOADMORE_FAIL
}

export default {
  COUNTER_INCREASE,
  COUNTER_DECREASE
}